language: java
jdk:
  - openjdk6
#  - openjdk7
before_script:
  - mysql -u root -e "drop database if exists dmdb2013;"
  - mysql -u root -e "create user dmdb@localhost identified by '1234';"
  - mysql -u root -e "create database dmdb2013;"
  - mysql -u root -e "grant all on dmdb2013.* to dmdb@localhost;"
  